module.exports = {
  "tuna"            :"bj",
  "opentuna"        :"nx",
  "bfsu"            :"bj",
  "bjtu"            :"bj",
  "njupt"           :"js",
  "tongji"          :"sh",
  "cqu"             :"cq",
  "uestc"           :"sc",
  "hit"             :"hl",
  "nju"             :"js",
  "hust"            :"hb",
  "neusoft"         :"ln",
  "lzu"             :"gs",
  "neu"             :"ln",
  "pku"             :"bj",
  "bupt"            :"bj",
  "byrio"           :"bj",
  "cqupt"           :"cq",
  "ynuosa"          :"yn",
  "xjtu"            :"sn",
  "xtom"            :"  ",
  "xtom-hk"         :"hk",
  "xtom-de"         :"  ",
  "xtom-nl"         :"  ",
  "xtom-ee"         :"  ",
  "wsyu"            :"hb",
  "sdu"             :"sd",
  "xidian"          :"sn",
  "njtech"          :"js",
  "geekpie"         :"sh",
  "https://mirrors.ustc.edu.cn/static/json/mirrorz.json"   :["ustc"    ,"ah"],
  "https://mirror.sjtu.edu.cn/mirrorz/siyuan.json"         :["siyuan"  ,"sh"],
  "https://mirrors.sjtug.sjtu.edu.cn/mirrorz/zhiyuan.json" :["zhiyuan" ,"sh"],
  "https://mirrors.dgut.edu.cn/static/mirrorz.json"        :["dgut"    ,"gd"],
  "https://mirrors.sustech.edu.cn/mirrorz/mirrorz.json"    :["sustech" ,"gd"],
  "https://mirrors.nwafu.edu.cn/api/mirrorz/info.json"     :["nwafu"   ,"sn"],
  "https://mirror.iscas.ac.cn/.mirrorz/mirrorz.json"       :["iscas"   ,"bj"],
  "https://mirrors.zju.edu.cn/api/mirrorz.json"            :["zju"     ,"zj"],
  "https://mirrors.scau.edu.cn/mirrorz.d.json"             :["scau"    ,"gd"],
  "https://mirror.nyist.edu.cn/mirrorz.json"               :["nyist"   ,"ha"],
}
