module.exports = {
  "tuna"            :"bj",
  "opentuna"        :"nx",
  "bfsu"            :"bj",
  "bjtu"            :"bj",
  "njupt"           :"js",
  "tongji"          :"sh",
  "cqu"             :"cq",
  "uestc"           :"sc",
  "hit"             :"hl",
  "nju"             :"js",
  "hust"            :"hb",
  "neusoft"         :"ln",
  "lzu"             :"gs",
  "neu"             :"ln",
  "nyist"           :"ha",
  "scau"            :"gd",
  "zju"             :"zj",
  "pku"             :"bj",
  "byrio"           :"bj",
  "cqupt"           :"cq",
  "ynuosa"          :"yn",
  "xjtu"            :"sn",
  "xtom"            :"  ",
  "xtom-hk"         :"hk",
  "xtom-de"         :"  ",
  "xtom-nl"         :"  ",
  "xtom-ee"         :"  ",
  "wsyu"            :"hb",
  "https://mirrors.ustc.edu.cn/static/json/mirrorz.json" :["ustc"    ,"ah"],
  "https://mirror.sjtu.edu.cn/mirrorz/siyuan.json"       :["siyuan"  ,"sh"],
  "https://mirror.sjtu.edu.cn/mirrorz/zhiyuan.json"      :["zhiyuan" ,"sh"],
  "https://mirrors.dgut.edu.cn/static/mirrorz.json"      :["dgut"    ,"gd"],
  "https://mirrors.sustech.edu.cn/mirrorz/mirrorz.json"  :["sustech" ,"gd"],
  "https://mirrors.nwafu.edu.cn/api/mirrorz/info.json"   :["nwafu"   ,"sn"],
}
