module.exports = {
  "https://mirrorz.org/static/json/legacy/tuna.json"            :"bj",
  "https://mirrorz.org/static/json/legacy/opentuna.json"        :"  ",
  "https://mirrorz.org/static/json/legacy/bfsu.json"            :"bj",
  "https://mirrors.ustc.edu.cn/static/json/mirrorz.json"        :"ah",
  "https://mirror.sjtu.edu.cn/mirrorz/siyuan.json"              :"sh",
  "https://mirror.sjtu.edu.cn/mirrorz/zhiyuan.json"             :"sh",
  "https://mirrors.dgut.edu.cn/static/mirrorz.json"             :"gd",
  "https://mirrors.sustech.edu.cn/mirrorz/mirrorz.json"         :"gd",
  "https://mirrors.nwafu.edu.cn/api/mirrorz/info.json"          :"sn",
  "https://mirrorz.org/static/json/legacy/bjtu.json"            :"bj",
  "https://mirrorz.org/static/json/legacy/njupt.json"           :"js",
  "https://mirrorz.org/static/json/legacy/tongji.json"          :"sh",
  "https://mirrorz.org/static/json/legacy/cqu.json"             :"cq",
  "https://mirrorz.org/static/json/legacy/uestc.json"           :"sc",
  "https://mirrorz.org/static/json/legacy/hit.json"             :"hl",
  "https://mirrorz.org/static/json/legacy/nju.json"             :"js",
  "https://mirrorz.org/static/json/legacy/hust.json"            :"hb",
  "https://mirrorz.org/static/json/legacy/neusoft.json"         :"ln",
  "https://mirrorz.org/static/json/legacy/lzu.json"             :"gs",
  "https://mirrorz.org/static/json/legacy/neu.json"             :"ln",
  "https://mirrorz.org/static/json/legacy/nyist.json"           :"ha",
  "https://mirrorz.org/static/json/legacy/scau.json"            :"gd",
  "https://mirrorz.org/static/json/legacy/zju.json"             :"zj",
  "https://mirrorz.org/static/json/legacy/pku.json"             :"bj",
  "https://mirrorz.org/static/json/legacy/byrio.json"           :"bj",
  "https://mirrorz.org/static/json/legacy/cqupt.json"           :"cq",
  "https://mirrorz.org/static/json/legacy/ynuosa.json"          :"yn",
  "https://mirrorz.org/static/json/legacy/xjtu.json"            :"sn",
  "https://mirrorz.org/static/json/legacy/xtom.json"            :"  ",
  "https://mirrorz.org/static/json/legacy/xtom-hk.json"         :"hk",
  "https://mirrorz.org/static/json/legacy/xtom-de.json"         :"  ",
  "https://mirrorz.org/static/json/legacy/xtom-nl.json"         :"  ",
  "https://mirrorz.org/static/json/legacy/xtom-ee.json"         :"  ",
  "https://mirrors.wsyu.edu.cn/.mirrorz/mirrorz.json"           :"hb",
}
