name: Trigger cf pages build if any change

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build if there is any change
        env:
          CF_TRIGGER: ${{ secrets.CF_TRIGGER }}
        run: |
          A=$(curl -s https://mirrorz.org/version   | grep json_legacy | cut -d ' ' -f 2)
          B=$(curl -s https://mirrors.bj.cn/version | grep json_legacy | cut -d ' ' -f 2)
          [ "$A" != "$B" ] && curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${CF_TRIGGER}
